name: Django Poll Test

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  simple_build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python 3.7
        uses: actions/setup-python@v3
        with:
           python-version: 3.7
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Run tests
        run: |
            cd mysite
            python manage.py test polls